version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - echo "CDK_DEFAULT_REGION=${AWS_DEFAULT_REGION}" > env.sh
      - echo "CDK_DEFAULT_ACCOUNT=`echo $CODEBUILD_BUILD_ARN  |tr ':', ' ' |awk {'print $5'}`" >> env.sh
      - . ./env.sh && mvn clean package && cdk synthesize
      - cp cdk.out/AppStack.template.json template.json

artifacts:
  files:
    - template.json
  discard-paths: yes