version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - mvn clean package && cdk synthesize
      - find .
      - cp cdk.out/AppStack.template.json template.json

artifacts:
  files:
    - template.json
  discard-paths: yes